[package]
name = "bp3d-tracing"
version = "0.1.0"
authors = ["Yuri Edward <yuri6037@outlook.com>"]
edition = "2018"
description = "Tracing subscriber implementations for use with BP3D software. Supports traditional logging through bp3d-logger and supports remove profiling through TCP."
license = "BSD-3-Clause"
repository = "https://gitlab.com/bp3d/bp3d-tracing"
readme = "./README.MD"
keywords = []
categories = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.32"
tracing-core = "0.1.24"
time = "0.3.9"