name: Development

on:
  - push
  - workflow_dispatch

jobs:
  test-build:
    uses: BlockProject3D/workflows/.github/workflows/Build_Test.yml@main

  analyze:
    uses: BlockProject3D/workflows/.github/workflows/Analyze.yml@main
    needs: test-build

  release:
    uses: BlockProject3D/workflows/.github/workflows/Release.yml@main
    needs: test-build
    secrets:
      RELEASE_TOKEN: "this is not a secret"
